apiVersion: radanalytics.redhat.com/v1
kind: SparkCluster
metadata:
  clusterName: "sparkle"
  labels:
    radanalytics: sparkcluster
  name: "sparkle"
  namespace: myproject
spec:
  Image: radanalyticsio/openshift-spark:2.2-latest
  SparkMasterName: sparkle-spark-master
  SparkWorkerName: sparkle-spark-worker
  sparkmetrics: prometheus
  workers: 3
status:
  message: Created, not processed yet
  state: created
