apiVersion: radanalytics.redhat.com/v1
kind: SparkCluster
metadata:
  clusterName: "hk"
  labels:
    radanalytics: sparkcluster
  name: "hk"
namespace: myproject
spec:
  Image: radanalyticsio/openshift-spark:2.2-latest
  SparkMasterName: hk-spark-master
  SparkWorkerName: hk-spark-worker
  sparkmetrics: prometheus
  notebook: jupyter
  workers: 5
status:
  message: Created, not processed yet
  state: created
