apiVersion: radanalytics.redhat.com/v1
kind: SparkCluster
metadata:
  clusterName: "erik"
  labels:
    radanalytics: sparkcluster
  name: "erik"
namespace: myproject
spec:
  Image: radanalyticsio/openshift-spark:2.2-latest
  SparkMasterName: erik-spark-master
  SparkWorkerName: erik-spark-worker
  sparkmetrics: prometheus
  alertrules: uptime
  workers: 7
status:
  message: Created, not processed yet
  state: created
